### ISSUE TITLE
MQ2 gas sensor

### ISSUE THREAD

**Issue by tzabbi** [ControlEverythingCommunity/CE_PYTHON_LIB#3]
Hey there,

I use this ADC and want to connect a MQ2 gas sensor.
Your script works and give me a row_adc value.
The MQ 2 sensor measures different gases for example Smoke, CO, and so on.
Do you know how I can read this diffent values about ADC?

tzabbi

**Comment by zaphod-42** [comment]
You cannot differentiate between gasses using this sensor, it only reports ppm of applicable gasses in the air
